AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a Route53 Record Set and IAM credentials which can update it.

Parameters:
  IP:
    Description: the IP address that the record will point to
    Type: String

  HostedZoneName:
    Description: the hosted zone name that the record set will be made in
    Type: String

  Subdomain:
    Description: the name of the record set
    Type: String
    Default: home

Resources:
  RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Name: !Sub
        - "${Subdomain}.${HostedZoneName}"
        - Subdimain: !Ref Subdomain
          HostedZoneName: !Ref HostedZoneName
      Type: A
      ResourceRecords:
        - !Ref IP
      TTL: 60

